blank_issues_enabled: true
contact_links:
  - name: Prywatne zgłoszenie e-mail
    url: mailto:gearsoul00@gmail.com
    about: Wyślij raport prywatnie, jeśli załączniki zawierają dane techniczne, których nie chcesz publikować.
